comment: off

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        target: auto
        threshold: 0.1%

ignore:
  - "pynetdicom/tests"
  - "pynetdicom/apps"
  - "pynetdicom/benchmarks"
  - "pydicom-master"
