name: docs-release

on:
  push:
    branches: -'[0-9].[0-9].X'

jobs:

  sphinx:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8]

    steps:
    - name: Get branch name
      # Should be 1.2.X, 2.5.X, etc
      run: echo ${GITHUB_REF##*/}
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "apt-get update -y && apt-get install -y git"
        build-command: "make html"
    - name: Commit changes to gh-pages
      run: |
        git clone https://github.com/pydicom/pynetdicom.git --branch gh-pages --single-branch gh-pages
        BRANCH=${GITHUB_REF##*/}
        cp -r docs/_build/html/* gh-pages/${BRANCH::-2}
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update docs from commit ${GITHUB_SHA}" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Merge changes to gh-pages
      if: ${{ success() }}
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
