name: docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  sphinx:
    # Matrix builds with development pydicom
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib sphinx pillow sphinx_rtd_theme numpydoc sphinx-gallery sphinxcontrib-napoleon sphinx-issues~=1.0
        pip install git+https://github.com/pydicom/pydicom
    - name: Build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - name: Deploy
      if: ${{ success() }}
      uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/html/
