name: docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  sphinx:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "apt-get update -y && apt-get install -y git"
        build_command: "make html"
