name: docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  sphinx:
    # Matrix builds with development pydicom
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8]

    steps:
    - name: Check stuff
      run: |
        echo $PATH && which git
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
